
try
{

}
catch(e)
{

}

fetch("url").then(data => {
    console.log(data)
}).catch(error => {
    console.log(error)
})